---
- hosts: webserver
  become: yes
  tasks:
  - name: for linux command
    command: hostname -f
    register: myresult
  - name: display result
    debug:
     msg: "{{myresult}}"
  - name: install git
    apt: 
     name: git
     state: present
    when: myresult.stderr ==""
  - name: tree
    apt:
     name: tree
     state: present
    when: myresult.stderr !=""
   
