---
- hosts: webserver
  become: yes
  tasks: 
  - name: install java on ubuntu servers
    apt:
     name: "{{ubuntujava}}"
     state: present
    when: ansible_os_family=="debian"
  - name: install java on redhat servers
    yum:
     name: "{{redhatjava}}"
     state: present
    when: ansible_os_family=="RedHat"

