- hosts: all
  become: yes
  tasks:
   - name: installing git 
     apt:
      name: git
      state: present
   - name: installing maven
     apt:
      name: maven
      state: present   
      update_cache: yes
