---
- hosts: all
  tasks:
   - name: installing tree
     apt:
      name: tree
      state: present
   - name: installing webserver
     apt:
      name: apache2
      state: present 
   - name: service restart
     service:
      name: apache2
      state: started
   - name: installing wget
     apt:
      name: wget
      state: present  
       
