---
- hosts: all
  become: yes
  tasks:
   - name: installing apache2
     apt:
      name: apache2
      state: present
   - name: installing wget
     apt:
      name: wget
      state: present
   - name: checking service
     service:
      name: apache2
      state: started
      enabled: yes     

