---
- hosts: webserver
  become: yes
  tasks:
  - name: installing tomcat8 on ubuntu server
    apt:
     name: tomcat8
     state: present
     update_cache: yes
    when: ansible_os_family == "Debian"
  - name: starting service
    service:
     name: tomcat8
     state: started
    when: ansible_os_family == "Debian"
  - name: installing tomcat8 on redhat server
    yum:
     name: tomcat8
     state: present
     update_cache: yes
    when: ansible_os_family == "RedHat"
  - name: starting service
    service:
     name: tomcat8
     state: started
    when: ansible_os_family == "RedHat"
  - name: replacing ports for ubuntu server
    replace:
     regexp: '8080'
     replace: '9090'
     path: /etc/tomcat8/server.xml
    when: ansible_os_family == "Debian"
  - name: replcae port no with 9091 for redhat
    replace:
     regexp: '8080'
     replace: '9091'
     path: /etc/tomcat8/server.xml
    when: ansible_os_family == "RedHat"
  - name: checking tomcat on browser for ubuntu
    uri:
     url: https://18.224.182.118:9090
     status: 200
    when: ansible_os_family == "Debain"
  - name: checking tomcat on rowser for redhat
    uri:
     url: https://3.133.139.73:8080
     status: 200
    when: ansible_os_family == "RedHat"
