---
- hosts: webserver
  become: yes
  tasks:
  - name: installing webserver on ubuntu
    apt:
     name: "{{ubuntu}}"
     state: present
    when: ansible_os_family =="Debian"
  - name: restarting service
    service:
     name: "{{ubuntu}}"
     state: started
    when: ansible_os_family =="Debian"
  - name: installing webserver on redhat
    yum:
     name: "{{redhat}}"
     state: present
    when: ansible_os_family =="RedHat"
  - name: starting services
    service:
     name: "{{redhat}}"
     state: started
    when: ansible_os_family =="RedHat"

