---
- name: deploy java application
  get_url:
    url: http://3.135.187.87:8081/artifactory/MYUAT/18/target/mahaLogin-1.0.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    username: admin
    password: password
    force_basic_auth: yes
